### ISSUE TITLE
how to load events from server

### ISSUE THREAD

**Issue by abdulkadhir** [Pulstarter/ionic2-calendar#1]
I want to load an event from the server.
my API is
` [

    {
        "event_title": "Holiday",
        "event_description": "Holiday",
        "event_type": "Holiday",
        "start_time": "2017-12-15",
        "end_time": "2017-12-15"
    },
    {
        "event_title": "Holiday",
        "event_description": "Holiday",
        "event_type": "Holiday",
        "start_time": "2017-12-12",
        "end_time": "2017-12-12"
    }
]`

can you help me with this

**Comment by Pulstarter** [comment]
Hi!

I would pass your array of objects via an Input() property to the component::

`@Input() events=  [];`

And initialize it on the component. Then, you can adapt the component dates to fit yours, and in the for loop of line 76 you can check for them.

Hope it helps!

**Comment by abdulkadhir** [comment]
thanks, I'll check and reply
Is the JSON format is okay or I need to change the format

**Comment by Pulstarter** [comment]
Nice! The JSON format is ok.

**Comment by abdulkadhir** [comment]
can you send sample snippet for this
thanks

**Comment by Pulstarter** [comment]
Well, on line 79 you have the day, the month and the year, so you can do below it:

```
var my_day = this.year + '-' + (this.month + 1) + '-' + day;

if (this.events.start_time == my_day) {
	// Create an array pf events and fill it
	// to search for it when displaying the cells
}
```

This is only an idea. The rest of the implementation it's yours :-D

Regards!
